version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21

  pre_build:
    commands:
      - mvn -B clean test

  build:
    commands:
      - mvn -B package -DskipTests

  post_build:
    commands:
      - rm -rf deploy app-bundle.zip
      - mkdir -p deploy
      - cp target/*.jar deploy/app.jar
      - echo "web: java -XX:MaxRAMPercentage=75 -jar app.jar" > deploy/Procfile
      - cd deploy
      - zip -r ../app-bundle.zip ./*
      - cd ..
      - unzip -l app-bundle.zip | head -n 30

artifacts:
  files:
    - app-bundle.zip