version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - mvn -version

  pre_build:
    commands:
      - mvn -B clean test

  build:
    commands:
      - mvn -B package -DskipTests

  post_build:
    commands:
      - mkdir -p deploy
      - cp target/*.jar deploy/app.jar
      - cp Procfile deploy/Procfile
      - cd deploy
      - zip -r ../app-bundle.zip .
      - cd ..

artifacts:
  files:
    - app-bundle.zip