version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - "echo install"
      - "mvn -version"

  pre_build:
    commands:
      - "echo pre_build"
      - "mvn -B clean test"

  build:
    commands:
      - "echo build"
      - "mvn -B package -DskipTests"

  post_build:
    commands:
      - "echo post_build"
      - "mkdir -p deploy"
      - "cp target/*.jar deploy/app.jar"
      - "echo 'web: java -jar app.jar' > deploy/Procfile"

artifacts:
  files:
    - "app.jar"
    - "Procfile"
  base-directory: deploy